dependencies {
    // 공통 모듈 (BaseEntity, Message Response DTO)
    implementation project(":Global-module")

    // Eureka 클라이언트
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

    // Feign 클라이언트
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Map Struct
    implementation 'org.mapstruct:mapstruct:1.5.3.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.3.Final'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

    runtimeOnly 'org.postgresql:postgresql'
}
