server:
  port: 8082  # 각 마이크로서비스의 고유 포트 (Order-Service의 경우 예시로 8082 사용)

spring:
  application:
    name: ORDER-SERVICE  # 서비스 이름을 설정하여 Eureka에 등록될 때 사용

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  # Eureka 서버의 URL
